name: Build PdfToImage EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole PdfToImage.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PdfToImage-EXE
          path: dist/PdfToImage.exe
